#!/bin/bash
set -euo pipefail

ROOT=$(pwd)
for directory in $BUILDKITE_PLUGIN_FOR_EACH_DIRECTORY_PARENT/*; do
    echo "--- Changing working directory to $BUILDKITE_PLUGIN_FOR_EACH_DIRECTORY_PARENT/$directory"
    cd $directory
    $BUILDKITE_COMMAND
    cd $ROOT
done
